repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.12.12
      hooks:
        # Run the linter
        - id: ruff
          args: [ --fix ]
        # Run the formatter
        - id: ruff-format
    - repo: https://github.com/compilerla/conventional-pre-commit
      rev: v3.4.0
      hooks:
        - id: conventional-pre-commit
          stages: [commit-msg]