name: Ruff Linting

on:
    push:
        branches: [ main, develop ]
    pull_request:
        branches: [ main ]

jobs:
    ruff:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
        
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'

            - name: Install ruff
              run: pip install ruff
            
            - name: Run ruff check
              run: ruff check .
            
            - name: Run ruff format check
              run: ruff format --check .